### ISSUE TITLE
what is the attribute for an id  for Zoobank. Phycobank etc,

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#56]
how is the MycobankId annotated: 844399  and why? 

`<object-id xlink:type="simple" object-id-type="MycoBank">844399</object-id>`

or

`<object-id xlink:type="simple" object-id-type="MycoBank">http://phycobank.org/844399</object-id> `

or 

`<ext-link ext-link-type="uri" xlink:href="http://phycobank.org/844399">http://phycobank.org/844399</ext-link>`

or

`<named-content content-type="phycobank" xlink:href="http://phycobank.org/103328">Phycobank 103328</named-content>`

**Comment by tcatapano** [comment]
`<object-id> is defined as "Unique identifier (such as a DOI or URI) for a component within an article (for example, for a figure or a table)." That is, it is an identiifer for an object in a publication, like a table, figure, section, treatment, etc... (https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html)

`<ext-link>` is defined as "Link to an external file or resource.", i.e, a uri which will create a hyperlink to an extrnal resource. Note that the usage guidelines distingguish it from the `<uri>` element: "Loosely put, an external link ) element is intended to act as a link; a URI [<uri>](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/uri.html) element identifies a URI (such as a URL) in the text, but may or may not be a traversable link" See: 

https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/ext-link.html

and

https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/uri.html

`<named-content>` is defined as "Word or phrase whose content/subject matter has distinct semantics or content-related significance.". I.e.,it is a generic element which could be used for fairly anything.

In the case of a mycobank identifier `<exit-link>` is probably the least best option, because it is not really declaring that the the tagged content is an identifier, just a link. `<named-content>` could be used, but its semantics are :"weaker" than the more specific `<object-id>` and <`uri>`. Strictly speaking, `<uri>` is probably the best option. *if* the identifier is indeed a URI. By my read `<object-id>` may be inappropriate as its arguable that the identifier string lijke the mycobank id is *citing* something external, not providing an identifierso that a component/object of the article can itself be cited.

**Comment by myrmoteras** [comment]
@tcatapano now I am confused.

here you write  `That leaves<named-content> as the best way to mark something as an identifier when it is not a URI` and in the email you metion p28 for a correct example. But this one is using `<object-id>`

`<tp:material-citation>
                <object-id content-type="arpha">B5596AA1-CDF9-DDA3-D5CD-D922E1723751</object-id>
`
